- src/Makefile
Makefileのobjclean:に「./eval/nnue/*.o」等を追加しました。
StockfishのNNUE評価関数、とても興味深く期待しております。
> Makefileのobjclean:に「./eval/nnue/*.o」等を追加

- src/position.cpp
nullmoveとpromotionの場合に評価値の差分計算と全計算の結果が異なっていたのを修正しました。
適当にデバッグログを入れてbenchコマンドを実行し、差分計算と全計算の差異が無くなったことを確認しました。
・nullmove
　やねうら王にあわせて、do_null_move()に「st->accumulator.computed_score = false;」を追加しました。
・promotion
　例えば2二のPawnが2一でQueenに成った場合、
　　old_pieceは「2二のPawn」
　　new_pieceは「2一のQueen」
　が正しい値かと思いますが、
　これまではold_pieceが「2一のPawn」になっていたようです。
　do_move()内のpromotionの処理のところで、old_pieceを上書きしている行をコメントアウトしました（old_pieceは既に設定済みの値のままでよさそうでしたので）。
　また、その上の行の「dp.pieceNo[0] = piece_no0;」は元々常に等しいようでしたので、ついでにコメントアウトしました。
> nullmoveとpromotionの場合に評価値の差分計算と全計算の結果が異なっていたのを修正

- src/extra/sfen_packer.cpp
set_from_packed_sfen()でmirrorをepSquareにも適用するように修正しました。
手元で少し学習を回してみました限りでは、learnコマンド実行時にqsearchのpvにillegal moveが含まれる旨ログ出力されるのはmirrorありの場合だけだったため、mirror処理を少し疑ってみました次第です。
もしかするとcastlingRightsにもmirrorを適用しなければならない可能性もあるかもしれませんが、私の理解が及んでおりません...
> set_from_packed_sfen()でmirrorをepSquareにも適用するように修正

- src/Makefile
こんばんは。
Stockfish + NNUE、早速コンピュータチェスの開発者の方が学習を開始されたようです！
http://talkchess.com/forum3/viewtopic.php?f=2&t=74059&start=10
https://groups.google.com/forum/#!topic/fishcooking/UnLEeExddxY
ただ、"Warning! OpenMP disabled." が出力されていて遅いとのことです。
Makefileを見ますと、OpenBLASの方は有効化されていましたが、OpenMPの方は有効化されていないようでしたので、有効化してみました。
※今このコメントを書いていて気付いたのですが、このプルリクエストでは-fopenmpをnnue-learn-use-blasにだけ追加したのですが、nnue-gen-sfen-from-original-eval等にも追加した方がよかったかもしれません...
> OpenMPの有効化

- src/evaluate.h
- src/uci.cpp
こんばんは。
Discordの#sf-nnue-devで
> Does SF NNUE have a way to show the static eval for a specific position? No search, just eval
と話題にあがっていましたので、eval_nnueコマンドを追加してみました。
> eval_nnueコマンド追加

- src/misc.h
Otherwise compiling with 'modern' or 'avx2' architecture on Linux aborts with errors.
> Adding mm_malloc.h

- src/eval/nnue/architectures/halfkp-cr-ep_256x2-32-32.h
- src/eval/nnue/architectures/halfkp_256x2-32-32.h
- src/eval/nnue/architectures/k-p-cr-ep_256x2-32-32.h
- src/eval/nnue/architectures/k-p-cr_256x2-32-32.h
- src/eval/nnue/architectures/k-p_256x2-32-32.h
- src/eval/nnue/evaluate_nnue.cpp
Use "nn.bin found & loaded" or "nn.bin not loaded" (file not found, read error, or UCI option SkipLoadingEval true)
Also, print "Error! nn.bin not found or wrong format" and continue...instead of exiting the program (looks like a crash).
> "nn.bin found & loaded" 

- src/learn/learner.cpp
- src/types.h
This fixes a possible bug in learner.cpp.
A position with no legal moves for the side-to-move can either be mate (if the side-to-move is in check) or stalemate.
We simply look for checking pieces to know if the side-to-move is being checked or not.
Also re-add an include in types.h which was deleted upstream.
> Stalemate fix

- src/learn/learner.cpp
こんにちは。
pgn-extract形式のファイルを教師局面のbinファイルへ変換するコマンドを作成してみました。
pgnファイルからbinファイルへ直接変換ではなく、事前にpgn-extractコマンドによる変換が必要です。
以下の手順でbinファイルへ変換し、変換後のbinファイルで少し学習を回してみまして、（おそらく）問題なく動作することを確認しました。
http://rebel13.nl/download/data.html
Download Selected Lichess games
```
pgn-extract --fencomments -Wlalg --nochecks --nomovenumbers --noresults -w500000 -N -V -o comp-2019-06.txt comp-2019-06.pgn
stockfish.exe
setoption name SkipLoadingEval value true
isready
learn convert_bin_from_pgn-extract output_file_name fens_comp-2019-06.bin comp-2019-06.txt
```
※Qhapaqさんと競合したいわけではありません。
　チェスの開発者の中にはpythonに慣れている方もいらっしゃればpgn-extractコマンドに慣れている方もいらっしゃると思いますので
　両方あった方が便利かと思いました次第です。
　もし似たような変換コマンドが2つあると混乱するようでしたら、Pull Requestを取り下げいたします。
> learn convert_bin_from_pgn-extractコマンドを追加

- src/learn/learner.cpp
こんにちは。
convert_bin_from_pgn-extractコマンドをアップデートしました。
(1) fishtestのpgnファイルに対応
(2) pgnファイルの評価値に100ではなくPawnValueEg（206）を掛けるように修正
上記(1)に伴い、pgn_eval_side_to_moveオプション（0または1）を追加しました。
このオプションの使用方法は以下のとおりです。
```
http://rebel13.nl/download/data.html
Download Selected Lichess games
pgn-extract --fencomments -Wlalg --nochecks --nomovenumbers --noresults -w500000 -N -V -o comp-2019-06.txt comp-2019-06.pgn
stockfish.exe
learn convert_bin_from_pgn-extract pgn_eval_side_to_move 0 output_file_name fens_comp-2019-06.bin comp-2019-06.txt
```
```
https://github.com/glinscott/fishtest/wiki/PGN-files-of-games-played-on-fishtest
pgn-extract --fencomments -Wlalg --nochecks --nomovenumbers --noresults -w500000 -N -V -o fishtest.txt fishtest.pgn
stockfish.exe
learn convert_bin_from_pgn-extract …
```
> updated convert_bin_from_pgn-extract

- src/Makefile
This allows building modern compiles with SSE41 enabled,
which gives a nice speedup on my Bulldozer CPU.
For example:
make nnue ARCH=x86-64-modern sse41=yes -j
> Add SSE41 switch.

- Readme.md
- src/search.cpp
- src/uci.cpp
- src/uci.h
- src/ucioption.cpp
こんばんは。
official-stockfishでつい最近導入された「WDL statistics」をマージしました。
https://github.com/official-stockfish/Stockfish/commit/110068808b51344ac59f8c6a0846f5dfdf670392
https://github.com/official-stockfish/Stockfish/pull/2778
https://github.com/official-stockfish/Stockfish/pull/2788
WDLというのはWin-Draw-Lossのことで、探索中にGUI側へ評価値や読み筋を送る際に
`info depth 59 seldepth 78 multipv 1 score cp 80 wdl 313 675 12 lowerbound nodes 3568397124 nps 2847848 hashfull 1000 tbhits 0 time 1253015 pv f3h4`
のようにWin-Draw-Lossの見積もりを千分率で送るようになったようです。
この機能を有効にするか否かはUCIオプション「UCI_ShowWDL」で指定するようです。
現在はデフォルト値trueですが、#2788でfalseに変わる模様です。
このプルリクエストでは、デフォルト値falseにしておきました。
WDLの導出方法は、
> The model this reporting uses is based on data derived from a few million fishtest LTC games,
> given a score and a game ply, a win rate is provided that …
> merge "Provide WDL statistics"

- src/eval/nnue/evaluate_nnue.cpp
- src/learn/learner.cpp
- src/learn/multi_think.cpp
- src/uci.cpp
- src/uci.h
- src/ucioption.cpp
instead of 'isready' command. This addresses #28 
**Main changes:**
- is_ready() renamed to init_nnue() and simplified, all calls to is_ready() replaced accordingly. There is no need to send empty lines which will at best be simply ignored. TT.resize() is automatically executed after a "setoption name Hash value xxx" anyway, and Search::clear() is done after "ucinewgame".
- The net will now be loaded after "ucinewgame", if necessary, and always after changing `EvalDir`.
- init_nnue() now included in both, the bench command and in the main UCI loop after receiving "ucinewgame" command. This will allow to do profile-builds with the NNUE net loaded.
> Rework loading the net after receiving 'ucinewgame'

- src/eval/nnue/evaluate_nnue.cpp
- src/eval/nnue/evaluate_nnue.h
- src/eval/nnue/nnue_test_command.cpp
- src/ucioption.cpp
Replace EvalDir with EvalFile
User can now browse filesystem for net (eval\nn.bin is default)
nn.bin no longer const
> UCI option EvalFile

- src/ucioption.cpp
Not sure how it is with Mac and Android, but for Linux in general `eval\nn.bin` as default path doesn't work.
> Default network path in Linux.

- src/eval/nnue/evaluate_nnue.cpp
- src/eval/nnue/evaluate_nnue.h
- src/eval/nnue/evaluate_nnue_learner.cpp
Currently there's a confusion between loaded network files and new network files that are saved after learning in path given by "EvalSaveDir". New network files are written in the path of loaded network files, overwriting them.
This PR corrects the issue, new network files are now saved as "nn.bin" in folder EvalSaveDir, old network is not overwritten.
Tested in both cases:
1) Training with `setoption name SkipLoadingEval value true`,
2) training with `setoption name SkipLoadingEval value false` and `setoption name EvalFile value oldnetwork/nn.bin`
> Saving new network in correct path.

- src/eval/nnue/evaluate_nnue_learner.cpp
> Use the path and filename for restoring parameter files.

- src/Makefile
- src/eval/nnue/layers/affine_transform.h
Hi @nodchip 
I'm a SF dev and very happy that you started the SFNNUE project.  If I may contribute here is a patch that adds AVX512 support.
I get a 4% speed up over AVX2.
```
Results for 40 tests for each version:
Base      Test      Diff      
Mean    1310045   1363423   -53378    
StDev   36898     46420     49766     
p-value: 0.858
speedup: 0.041
```
I didn't change kMaxSimdWidth from 32 to 64 because the padding is currently written out with the saved nets
and this would break reading existing nets that were saved with 32.  As a result there is a bit of extra code to handle cases that are not multiples of 64.  Once reading/writing the nets can handle different kMaxSimdWidth values this code can be removed.
Regarding the #if defined(\__MINGW32\__) || defined(\__MINGW64\__)
I would …
> Add AVX512 support

- src/Makefile
Tested on Windows gcc/mingw using
make profile-build ARCH=x86-64-avx512  -j
and
make profile-build ARCH=x86-64-avx512  COMP=mingw -j
I don't have access to a suitable Linux machine.
> Fix profile builds for AVX512

- src/learn/learner.cpp
- src/uci.cpp
- src/uci.h
こんばんは。
以前のプルリクエスト（ https://github.com/nodchip/Stockfish/pull/36 ）と同様に
評価関数の学習時にWDLを使うオプションを追加してみました。
`learn use_wdl 1 ...` のように指定すると、sigmoidを使うwinning_percentage()の代わりに
win rate modelによるWDLを用いた勝率を使うようになります。
以前のプルリクエストの際はクロスエントロピーの微分が難しく、一旦Revertして頂きました。
今回の実装では解析的な微分はあきらめて、数値微分にしました。
デバッグ用に、（WDLではなく）通常のsigmoidによる勝率の場合に
数値微分で計算した結果と、解析的な微分結果である(q - p)や(q - t)を比べると
誤差の範囲でほぼ一致することを確認しました。
（スケールをあわせるため、数値微分の結果をwinning_probability_coefficientで割っています）
最近導入されたconvert_teacher_signal_to_winning_probabilityが指定された場合にも対応したつもりです。
なお、LOSS_FUNCTIONとしては、今回はLOSS_FUNCTION_IS_ELMO_METHODにだけ対応しました。
ただ、手元で少し学習させてみましたところ、学習にはあまり効果がないようでした。（というより、逆効果でした）
※現在、機械学習バイナリのリリースに向けて、Stockfish masterマージ後のリグレッションテストを実施されている旨、twitterで拝見しました。
　このプルリクエストをマージして頂ける場合、次回リリース後で構いません。
> Use winning_percentage_wdl in learn

- src/learn/gensfen.cpp
- src/search.cpp
fixes valgrind errors as seen with:
```
setoption name Use NNUE value true
isready
gensfen depth 6 loop 10 use_draw_in_training_data_generation 1 eval_limit 32000 output_file_name training_data/training_data.bin use_raw_nnue_eval 0
quit
```
the latter script now runs without valgrind errors on linux
> Fix some uninitialized variables with gensfen

- .travis.yml
- src/Makefile
- src/nnue/evaluate_nnue.cpp
- src/ucioption.cpp
1) Only access UCI option if defined
2) disable -Werror for now.
3) disable a few target that don't have _mm_malloc.
4) Add profile-learn target, with small speedup.
5) just test on Linux + gcc (skip macOS, unclear openblas, skip linux+clang, unclear omp/std::filesystem).
> Fix small CI failures

- src/Makefile
- src/extra/sfen_packer.cpp
- src/learn/convert.cpp
- src/learn/gensfen.cpp
- src/learn/gensfen2019.cpp
- src/learn/learn.h
- src/learn/learner.cpp
- src/misc.cpp
- src/misc.h
This is some code cleanup of the part that wasn't touched in the previous one. Since I don't understand this part well I've limited myself to very simple changes. Only a few small functions were extracted, other than that mostly stylistycal changes and comment improvements. Most comments were left as is because they were already good or I couldn't understand them. I verified it shortly and seems to be functionally equivalent.
I have to clarify one thing before this is merged though. I noticed that there's `winning_percentage` that takes `ply` as a parameter (I think it was introduced by ttak and uses actual stockfish's wdl?). The thing is there was only one function that dispatched to it. Other functions were dispatching to the old `winning_percentage` overload that didn't consider the …
> Learner cleanup

- .travis.yml
- src/nnue/features/index_list.h
- src/search.cpp
- src/search.h
- src/ucioption.cpp
This pull request contains two changes:
- Changes the option name to prune at shallow depth on PV nodes more descriptive.
- Training -> PruneAtShallowDepthOnPvNode
- Sets the value of prune_at_shallow_depth_on_pv_node on a UCI option callback.
- Invert true/false of prune_at_shallow_depth_on_pv_node according to the option name.  The default behavior is not changed.
fixes #119
> Set the value of prune_at_shallow_depth_on_pv_node on a UCI option callback

- src/extra/nnue_data_binpack_format.h
- src/learn/gensfen.cpp
- src/learn/learner.cpp
- tests/instrumented_learn.sh
This PR introduces a new string option for `gensfen` named `sfen_format`. Valid values are `bin` (default) and `binpack`. This value determines the format to use for serializing the generated sfens. Output file extension is now chosen and added based on the chosen format, `output_file_name` should contain just the sfen. @noobpwnftw asked about this feature, so now there's at least a branch that implements it.
For learn the reader type is chosen on single file granularity based on its extension. `.bin` files are read directly, `.binpack` files are read entry by entry and converted to bin format before further processing.
nnue_data_binpack_format.h is a header-only library that exposes some functions related to plain, bin, and binpack formats. In particular it allows creating readers and …
> Introduce sfen_format option for gensfen. Experimental support for binpack format in gensfen and learn.

- src/tt.cpp
- src/tt.h
- src/ucioption.cpp
This pull request adds `EnableTranspositionTable` UCI option to enable/disable transposition table.  
In Discord, noobpwnftw asked if it is better to disable transposition table during training.  This is the option for it.
https://discordapp.com/channels/435943710472011776/737073080081317948/752744087936827502
> again, next issue:
https://github.com/nodchip/Stockfish/blob/e5f05fa2b9f60503e121102ba94390e6974ced1e/src/learn/learner.cpp#L847
During loss test, qsearch is used without clearing previous TT, this is also true for training, for training this is less harmful due to positions being shuffled and unique, however there are chances that they do hit and the progression of net performance cannot be properly measured if previous TT is available, this largely affects loss function due to …
> Added EnableTranspositionTable UCI option to enable/disable transposition table.

- src/extra/nnue_data_binpack_format.h
- src/learn/convert.cpp
- src/uci.cpp
Add convert UCI command that allows conversion of files between any of plain, bin, and binpack. 
Usage: `convert infile outfile [append]`
I kept the old conversion routines because they have additional features. We should maybe consider moving them from learn to convert command in the future. Currently there's a weird coupling between learn and convert.
> UCI convert command

- src/extra/nnue_data_binpack_format.h
Compiling with MSVC fails without this include.
> Add missing include to make MSVC compile

- .travis.yml
- src/learn/learn.cpp
- src/ucioption.cpp
additionally allow all options to be converted to string.
Without this, restoring of the options (multi_think.cpp:117) can't work.
fixes https://github.com/nodchip/Stockfish/issues/128
Now gensfen/learn pass with debug=yes in CI
> Remove use of non-existent EvalDir option.

- src/learn/learn.cpp
This pull request changes the trainer to save the original net file to [EvalSaveDir]\original in the beginning of a training, and stores the folder path to `best_nn_directory` so that the trainer can load and restore the network parameters if the loss is not decreased at all.
Fixes #128
> Fixed a bug that an assertion fails in the trainer.

- src/learn/learn.cpp
This pull request fixes #152.  The results of experiments are in comments in #152.
Fixes #152
> Fixed a bug that the root color is wrong in get_shallow_value()

- src/learn/gensfen.cpp
- src/learn/learn.cpp
- src/learn/multi_think.h
- src/misc.h
This PR extends the ways the PRNG can be seeded. Now it can be seeded from either time, uint64, or string. Empty strings fallback to time. Also allows reseeding an existing PRNG. Strings are converted to uint64 by a murmur64 type hash.
`gensfen` and `learn` commands now support a `seed` option that takes either a string (in which case its hash is used) or a base 10 integer as a prng seed.
> PRNG seeding for gensfen and learn.

- src/learn/multi_think.cpp
- src/learn/multi_think.h
- src/search.cpp
- src/search.h
- src/syzygy/tbprobe.h
- src/thread.cpp
- src/thread.h
RootInTB was an incorrectly shared global, probably leading to wrong scoring
Minor:
setting TB global state from input by all threads (all threads write same values)
setting Limits global state by all threads (idem)
thread counting for finalization
CI can be enabled once races are fixed in the learner, manually goes like:
```
make clean && make -j2 ARCH=x86-64-modern sanitize=thread    optimize=no debug=yes build
../tests/instrumented_learn.sh --sanitizer-thread
```
Needs some review.
> Fix races in gensfen as detected with thread sanitizer.

- src/position.cpp
So that we only need to optimize Update/Refresh logic in one place, also let refresh triggers decide what to do.
> Optimize accumulators for null move.

- src/learn/learn.cpp
Simplify unnecessary variable.
> Fix a bug that LR is not correctly scaled when initial LR is not 1.0

- tests/instrumented.sh
- tests/instrumented_learn.sh
fixes some rare case where the master search thread makes no progress,
observed in CI.
> Use fair scheduling of threads under valgrind

- src/evaluate.cpp
This is helpful in both gensfen and training.
We do not need this:
https://github.com/nodchip/Stockfish/blob/6f7a2287079682e5710c10106dd60e3c76abcc3e/src/evaluate.cpp#L1029-L1030
However we do need to clamp evals, otherwise search can be affected by out of range eval scores.
Early versions had this clamp in NNUE code.
https://github.com/nodchip/Stockfish/blob/36092b855a5e2bcfb587a36e2055ea068e4bd8e5/src/eval/nnue/evaluate_nnue.cpp#L152
> Skip eval dampening in Use NNUE = pure case

- src/docs/binpack.md
- src/docs/convert.md
- src/docs/gensfen.md
- src/docs/learn.md
This is the first step to having well documented learn, gensfen, convert commands. Currently I documented their general purpose, invocation syntax, and briefly described parameters. Further work could focus on documenting recommended settings.
I allowed myself to skip writing documentation for shuffle and old convert stuff. Partially because I don't understand it well and partially because I consider it on its way out. What to do with this can be tackled in further PRs.
I also took a comment from one of old issues briefly describing the binpack format in put it in `docs/binpack.md` so that it's not completely forgotten.
Some things that I would like others to check and improve upon before merging this:
- `bat` and `minibatch` options in `learn` seems to be about the same thing. Also I …
> Initial documentation for learn, gensfen, convert, and binpack.

- src/docs/gensfen.md
- src/docs/learn.md
- src/learn/gensfen.cpp
- src/learn/learn.cpp
- src/learn/learn.h
- src/uci.cpp
- src/uci.h
This introduces a switch in learn and gensfen called `set_recommended_uci_options` which sets the most critical UCI options. There is still some discussion to be had on the exact options and values. For example setting "Contempt" to 0 for gensfen seems logical but I don't know if anyone does it.
This PR also changes the default parameters for learn and gensfen to be more in line with recent experiment results. Now this is even more questionable. For the start I applied moderate changes based on @noobpwnftw 's settings, but I didn't completely copy them. There are some parameters which are either subjective or questionable. The questionable ones are:
- noob sets `eval_limit` to 1000, which seems very low (default here is 3000)
- noob doesn't use draw adjudication (default here is to use …
> Change some learn and gensfen defaults. Add switch for setting recommended UCI options.

- src/extra/nnue_data_binpack_format.h
- src/learn/sfen_packer.cpp
This PR augments the .bin format (and also the .binpack format which relies on the .bin format) with the ability to store rule50 counts up to 127 (up from 63) and full move counts up to 65535 (up from 255). This change keeps the backward compatibility, the fix uses spare bits at the end of the bit stream. These bits are ignored by older versions, and old .bin files have them zeroed so it doesn't affect the value when read by the fixed version.
Fixes #75.
> Increase rule50 and fullmove counters range.

- docs/learn.md
- src/learn/learn.cpp
This PR adds a new option for `learn` `auto_lr_drop` that allows specifying for how many positions a single LR stage lasts. This allows having a deterministic LR drop schedule which is useful for reproducibility during testing.
> Add option "auto_lr_drop"

- src/learn/learn.cpp
- src/misc.h
This is a rewrite (restructuring) of the learner code so that it uses the newly added feature that allows execution of arbitrary tasks on stockfish's thread pool. In particular it:
- removes many parts of the code that were previously required for synchronization and task scheduling. 
- provides clearer distinction between single and multithreaded execution contexts
- makes the control flow more linear
- decouples SfenReader from LearnerThink
- removes [no longer] used parts of the learner
- removed old misleading comments and replaced them with new ones where necessary.
- adds `Entropy` struct to make passing and summing all the entropy statistics around the code easier
As this is a more or less a complete rewrite the diff is kinda hard to read, best to compare whole files side by side. …
> Make learner work on top of stockfish's thread pool instead of MultiThink.

- src/extra/nnue_data_binpack_format.h
- src/learn/learn.cpp
- src/learn/sfen_reader.h
- src/learn/sfen_stream.h
The following changes/bugfixes are made:
- Using an inexisting file is handled correctly and prints information in the console
- Unknown options are ignored instead of being treated as input file names
- Single input files can now be specified using the `targetfile <filename>` option.
- base_dir is now correctly applied to individual files.
> Improve handling of input files for learn.

- src/learn/convert.cpp
- src/learn/convert.h
- src/learn/learn.cpp
- src/uci.cpp
- tests/instrumented.sh
This PR moves the following legacy conversion commands from learn to dedicated uci commands:
- `convert_bin`
- `convert_plain`
- `convert_bin_from_pgn_extract`
> Move the old convert stuff from learn to their own commands.

- README.md
- docs/learn.md
- src/learn/learn.cpp
- src/learn/learn.h
- src/learn/sfen_reader.h
- tests/instrumented_learn.sh
This PR removes the `loop` parameter from training and adds an `epochs` parameter that controls for how many weight update cycles the training should last. It has the following advantages:
- no need to append the files `loop` times
- the sfen reader for learning now works in cyclic mode (sequential is still available) and loops indefinitely over the provided files
- this allows it to handle small amounts of data, previously end of files would be reached when filling the buffers and it was no clear how much data is needed to even start training (to start training one needed more data than for one iteration)
- files that don't contain any data are still removed from the file queue so it won't loop forever on nothing and still reach end of files
- it allows finishing the anticipated amount …
> Change training length from loops over data to the number of epochs

- docs/learn.md
- src/learn/learn.cpp
- src/learn/sfen_reader.h
- src/misc.cpp
- src/misc.h
- src/nnue/evaluate_nnue.cpp
- src/nnue/evaluate_nnue.h
- src/nnue/evaluate_nnue_learner.cpp
- src/nnue/evaluate_nnue_learner.h
- src/nnue/layers/affine_transform.h
- src/nnue/layers/clipped_relu.h
- src/nnue/layers/input_slice.h
- src/nnue/layers/sum.h
- src/nnue/nnue_feature_transformer.h
- src/nnue/trainer/trainer.h
- src/nnue/trainer/trainer_affine_transform.h
- src/nnue/trainer/trainer_clipped_relu.h
- src/nnue/trainer/trainer_feature_transformer.h
- tests/instrumented_learn.sh
This PR improves the diagnostics during learn by the following means:
- unification of the message format
- a `verbose` flag for `learn` that can be used to enable more granular diagnostics
- in `update_parameters` when `verbose == true` there is additional output regarding the gradients and the differences between evaluation of the discretized net and the trained net (they should be relatively close, otherwise things are wrong)
- display of layers and their indices in forward order before learning.
- display of layer name for which `check_health` is performed
- `check_health` for affine transform layer with average biases, weights, and last changes to them
- `check_health` in clipped relu and feature transformer shows the % of clipped outputs
- `check_health` in the feature transformer …
> Improve diagnostic messages during learn

- src/learn/gensfen.cpp
- src/learn/gensfen.h
- src/misc.h
- src/uci.cpp
- tests/instrumented_learn.sh
This PR makes the gensfen work on the stockfish's thread pool instead of using multithink. It also performs other minor changes:
- a collective parameter struct with clear defaults
- progress output is moved from sfen writer to gensfen and is more responsive
- sfen writer now correctly flushes the output when it's destroyed.
- clarity of the info messages is improved
- gensfen state is encapsulated better
- output is sychronized such that "created file" from sfen writer won't break the progress output from gensfen
- the race conditions that resulted in the number of emitted positions sometimes deviating from `loop_max` are now gone
- all parameters are printed
> Improve gensfen

- src/learn/learn.cpp
- src/learn/learn.h
- src/nnue/evaluate_nnue_learner.cpp
- src/nnue/evaluate_nnue_learner.h
Only `calc_grad` is used outside of `learn.cpp` and I think the place it's used is so far from the definition point and quite obscure that it makes sense to make the dependency explicit.
> Make all grad related functions in learn static. Pass calc_grad as a parameter.

- src/Makefile
- src/nnue/architectures/halfka_256x2-32-32.h
- src/nnue/evaluate_nnue_learner.cpp
- src/nnue/features/a.cpp
- src/nnue/features/a.h
- src/nnue/features/half_ka.cpp
- src/nnue/features/half_ka.h
- src/nnue/features/half_relative_ka.cpp
- src/nnue/features/half_relative_ka.h
- src/nnue/trainer/features/factorizer_half_ka.h
This PR adds code for HalfKA architecture along with all required infrastructure. HalfKA doesn't discriminate kings compared to HalfKP. A stands for "any piece" or alternatively "all pieces". Keep old architecture as the default one.
Noobpwnftw proposed that such an architecture would make more sense and I implemented it, and tests from additional pylon and me showed that it's not worse than HalfKP. Therefore I would like to at least put it on the master so that it's easier for people to experiment with.
I have to ask one thing though before this is merged. Since HalfKA factorizer uses PK features (that includes features king position) I removed the HalfK features from the factorizer (becuase my understanding is that it's already handled in PK features; in HalfKP there were only P …
> Add a HalfKA architecture

- src/Makefile
- src/extra/stockfish_blas.cpp
- src/extra/stockfish_blas.h
- src/thread.h
- src/uci.cpp
This PR introduces a set of blas routines optimized for SSE2 and parallelized using stockfish's internal thread pool. Currently unused, just added to the build.
Benchmarks and tests are added and can be called from UCI using commands "blasbench" and "blastest" respectively. They are only available when compiled with `USE_BLAS` as a reference point is required. On my i7-920 the custom implementation of sgemm on 4 threads is slightly faster than openblas in the benchmark. I haven't measured other functions yes, it will come next I guess.
> Add our own blas-like routines that use stockfish's thread pool.

- src/nnue/trainer/trainer_affine_transform.h
- src/nnue/trainer/trainer_feature_transformer.h
- src/nnue/trainer/trainer_input_slice.h
- src/nnue/trainer/trainer_sum.h
- src/thread.h
- tests/instrumented_learn.sh
This PR replaces the manual non-blas loops inside the trainers with our new implementation of blas-like routines. The interface is almost the same but for now I would like to keep clear separation between our and external blas. In the future we may consider coalescing the calls somehow.
This makes the compiles with `blas=no` about as fast on my setup as compiles with `blas=yes`. YMMV for >=AVX as it's not optimized for yet.
> Replace non-blas parts of trainers with our own blas-like routines.

- src/nnue/trainer/trainer_feature_transformer.h
This PR optimizes gradient clipping and statistics gathering in the feature transformer backprogation method. It's part of an effort to optimize all sequential code in the trainer. I tested this with a short training run and didn't note any anomalies.
> Optimize feature transformer backpropagation stats.

- src/nnue/trainer/trainer_clipped_relu.h
This optimizes the trainer clipped relu backpropagation. It's almost the same as in the feature transformer. It's part of an effort to optimize all sequential bits in the trainer. Tested with a small training run.
> Optimize trainer clipped relu backpropagate.

- src/nnue/trainer/trainer_feature_transformer.h
This PR replaces the use of OMP in the trainer feature transformer. It has the following advantages over the previous approach:
- We're not creating additional threads
- We don't rely on OMP to properly pool the threads
- We have better control over how the parallelization is done.
- Doesn't require OMP
Tested with a small training run at 4 threads.
> Replace omp in trainer_feature_transformer

- src/misc.h
- src/nnue/trainer/trainer_feature_transformer.h
This PR introduces a bitset that provides important guarantees about concurrent access. It allows each thread to independently work on different parts of the bitset. This new bitset is utilized in the trainer feature transformer to move the observed features counting loop to the parallelized one that already goes through the features. Also, previously the stride for threads was 1, not it is 512 so that the concurrent bitset access is possible and fast. This is in an effort to parallelize the sequential bits of the trainer.
> Move collection of observed features to a parallelized loop.

- docs/convert.md
- src/extra/nnue_data_binpack_format.h
- src/learn/convert.cpp
This PR adds optional validation of read moves in the training data conversion functions. `validate` can be added to the `convert` command, when this is done the conversion will stop on the first illegal move and print a diagnostic, for example 
`Illegal move f2f1 for position 8/8/8/8/8/4p1K1/3rkp2/R7 b - - 3 93` - here the promoted piece is missing.
It also fixes the bug that we were relying on the static initialization order (header only libraries considered harmful).
> Add optional move validation to training data conversion.

- src/extra/nnue_data_binpack_format.h
Otherwise on MACOS the read head is placed at the end when app is specified.
> Add explicit read head seek to the start of the binpack file.

- src/learn/gensfen.cpp
- src/learn/learn.cpp
- src/search.cpp
This PR adds an optional flag to gensfen `ensure_quiet` which when specified makes the generated positions be from the and of a qsearch. This is required for trainers that don't have qsearch, like the pytorch trainer.
It also adds an optional flag to learn `assume_quiet` which when specified makes `learn` not perform qsearch, making the training progress faster if the data is already only quiet positions.
> Support for only quiet generation and learning.

- src/learn/learn.cpp
Otherwise qsearch may end up in a terminal position. This was found by noob.
> Move the terminal position check to after qsearch

- docs/gensfen.md
- docs/learn.md
- src/learn/learn.cpp
This PR adds an option `smart_fen_skipping`. The name is not very telling because we want it to be easly extensible in the future without losing meaning.
Currently it allows skipping positions that have capture or promotion as best move, and position where a king is in check.
Trained without: https://tests.stockfishchess.org/tests/view/5fb9383a67cbf42301d6afbf
Trained with: https://tests.stockfishchess.org/tests/view/5fba952867cbf42301d6b0aa
> noobpwnftw: so for bestmove being capturing moves or so, it is obvious that naturally the gensfen will play this move and capture the piece, and in practice, SF likely try out captures without eval, or use SEE to check it, and the position eval does not contribute much to search decision, therefore, we skip them in training and the actual landing …
> Add skipping of bad learning examples.

- docs/transform.md
- src/Makefile
- src/learn/sfen_stream.h
- src/learn/transform.cpp
- src/learn/transform.h
- src/uci.cpp
This command will cover all data transformations that we happen to need in the future.
It is started by the need of vondele, who suggested creating training data with static evaluations slightly adjusted towards scores present in a given input file. This is implemented in this PR with the command `transform nudged_static`.
Example usage: `transform nudged_static absolute 10 input_file in.binpack output_file out.binpack`
> Transform command

- src/extra/stockfish_blas.cpp
- src/extra/stockfish_blas.h
- src/nnue/evaluate_nnue_learner.cpp
- src/nnue/trainer/trainer_affine_transform.h
- src/nnue/trainer/trainer_clipped_relu.h
- src/nnue/trainer/trainer_feature_transformer.h
- src/nnue/trainer/trainer_input_slice.h
- src/thread.h
In the current master the worker threads are launched many times during propagate/backpropagate passes. Most operations are too small to benefit from parallelization, and some are not parallelizable at all. This PR introduces a different approach. It splits the batch into num_threads parts and processes each batch part in one thread, all the way through `propagate` -> `calc_loss` -> `backward`. `step_start` and `step_end` are introduced as places to initialize for a batch and perform weight updates.
It seems faster on my 4 core machine, but I have no means of benchmarking this on higher core counts - and that's what I'm mainly trying to improve here. I believe this approach should scale much better to very high core counts. Before proceeding further with this I'd like to see some …
> [WIP] More coarse grained multithreading for forward/backward when learning.

- src/learn/autograd.h
- src/learn/learn.cpp
- src/learn/learn.h
- src/nnue/evaluate_nnue_learner.cpp
- src/nnue/evaluate_nnue_learner.h
This is a WIP PR for replacing the machinery around the loss function with a more robust approach based on automatic differentiation. The advantages are twofold: 1. We don't have to compute the loss derivatives. 2. Loss always matches its derivative.
Currently I allowed myself to remove all the old loss code and replace it with cross entropy based loss. That means `use_wdl` and teacher score rescaling have no effect right now. I would like to bring back at least the `use_wdl` option, but I'd have to understand it deeper and create necessary automatic differentiation primitives to represent stockfish's wdl function with it.
As it stands, I trained one network with this trainer and it turned out, as expected, about equal to the network trained with an older version (Baseline was halfka flip …
> Automatic differentiation for the loss function.

- src/Makefile
- src/learn/convert.cpp
- src/learn/gensfen.cpp
- src/learn/learn.cpp
- src/learn/sfen_writer.h
- src/nnue/evaluate_nnue_learner.cpp
- src/nnue/nnue_common.h
older versions of gcc (<8.1) need this, even if they accept -std=c++17
with this patch, the code can be run on fishtest again,
at least by the majority of workers (fishtest doesn't require c++17 to be available)
See e.g.
https://tests.stockfishchess.org/tests/view/5fcfbf801ac1691201888235
Bench: 3820648
> Add -lstdc++fs to the link line of gcc

- src/extra/nnue_data_binpack_format.h
from discord.
```
[11:25 PM] vondele: @Sopel I have the following .plain entry:
fen 5k2/2R5/6P1/8/6pP/2p2r2/6K1/8 b - h3 0 45
move f3h3
score 0
ply 89
result 0
e
../../src/stockfish convert test.plain test.binpack validate
yields:
Illegal move f3h3 for position 5k2/2R5/6P1/8/6pP/2p2r2/6K1/8 b - h3 0 45
```
This fixes it.
> Fix incorrect enpassant flag for moves read from uci format in the binpack lib

- README.md
- src/Makefile
In `ae045e2`, I unintentionally re-introduced deprecated commands. I reversed the issue and maintained mac-compatibility by moving the mac-required libraries to the right locations in the makefile.
> remove unnecessary makefile commands and fix blas on mac

- docs/transform.md
- src/learn/transform.cpp
This PR adds a basic rescoring tool. It can either take an .epd file with FENs as input or a .bin or .binpack file. The general description and options can be found in docs. The tool utilizes all threads as set by the UCI option. There is an additional option `keep_moves` which default to true and means that the moves from the input .bin/.binpack file are kept, this allows to keep the good compression if the positions were linked in the input file.
Usage example:
```
./stockfish.exe
uci
setoption name Threads value 4
setoption name PruneAtShallowDepth value false
isready
transform rescore in.binpack out.binpack depth 6 keep_moves 1
transform rescore in.epd out.binpack depth 6
quit
```
The tool might not scale well to many threads on very low depth rescorings as the sfen reader is …
> Rescoring tool.

- src/learn/learn.cpp
- tests/instrumented_learn.sh
Qsearch is not a pure function. It contains internal state like history tables. Noob has reported wild deviations for validation loss when continuing the training and they come from qsearch improving itself over time. This PR replaces the qsearch in validation loss computation with plain nnue evaluation. This is more in line with what happens in most of the search and is more deterministic.
> Use plain nnue eval for validation loss calculation instead of first performing qsearch

- docs/transform.md
- src/learn/transform.cpp
allows for repeating a depth N search K times.
Repeated searches improve the quality of eval, but don't bring in higher depth info.
Might allow for removing some of the noise in low depth scoring.
> allow for repeated searches in rescoring

- src/nnue/trainer/trainer_feature_transformer.h
Currently the weights are summed naively, but due to the factorizer some weights a sum of others. This causes the `avg_abs_weight` for the feature transformer during `check_health` to be computed incorrectly, and change after reloading the net.
> Correctly account for factors when computing the average absolute weight of the feature transformer.

- src/learn/learn.cpp
- src/learn/sfen_reader.h
Used to be 10M, now we bound it by a multiple of `validation_count`, and at most 1M. This reduces the RAM usage greatly.
> Reduce the amount of sfens buffered for the validation step.

- src/nnue/evaluate_nnue.cpp
bench repeatedly does `use nnue value true` `use nnue value false` and it constantly unloads and loads the evalfile. This makes the mixed bench meaningless. This PR makes it not unload the previously loaded evalfile. It's not needed to unload is, it's enough that useNNUE is set to false.
> Don't unload evalfile on set nnue false

- src/nnue/trainer/trainer_clipped_relu.h
- src/nnue/trainer/trainer_feature_transformer.h
> Accumulate clipping statistics to a 64 bit integer to prevent overflow for larger batch sizes.

- docs/learn.md
- src/learn/learn.cpp
Specified with `warmup_epochs`, uses `warmup_lr`.
The purpose is to put the net into a somewhat stable state so that the gradients are not as high during the early stages of the training and don't "accidentally" break the net.
Default values preserve the old behaviour.
Sample output:
```
INFO (initialize_training): Performing random net initialization.
Finished initialization.
info string NNUE evaluation using  enabled
INFO (sfen_reader): Opened file for reading: data/noob_master_d9_1B_0.binpack
INFO (sfen_reader): Opened file for reading: data/noob_master_d9_1B_0.binpack
Doing 10 warmup epochs.
.Finished 1 out of 10 warmup epochs.
.Finished 2 out of 10 warmup epochs.
.Finished 3 out of 10 warmup epochs.
.Finished 4 out of 10 warmup epochs.
.Finished 5 out of 10 warmup epochs.
.Finished 6 …
```
> Add optional warmup step for training.

- src/extra/nnue_data_binpack_format.h
This reverts commit 6afcdaa928c4b7a9711b3df53d4cbb70616975f5.
Some old binpacks seem to have been affected by this change and no longer can be converted back. This means that there were likely some false ep squares already in the historical data and fixing it breaks the encoding...
> Revert "Add additional checks for en-passant possiblity when fixing the erroneus ep flag from a fen."
