nodchip/Stockfish

src/Makefile
src/eval/nnue/evaluate_nnue.cpp

Add targets to Makefile, and fix build errors.
I used g++-8.1.0 on Ubuntu 16.04.

Build with gcc

---

src/Makefile
src/eval/nnue/nnue_test_command.cpp
src/eval/nnue/nnue_test_command.h
src/uci.cpp

こんにちは。
将来、コンピュータチェスの開発者の方々が独自にNNUEの特徴量を追加されるときのために
「test nnue test_features」等を有効化してみました。

「test nnue test_features」等の有効化

---

src/eval/nnue/architectures/halfkp-cr-ep_256x2-32-32.h
src/eval/nnue/architectures/halfkp_256x2-32-32.h
src/eval/nnue/architectures/k-p-cr-ep_256x2-32-32.h
src/eval/nnue/architectures/k-p-cr_256x2-32-32.h
src/eval/nnue/architectures/k-p_256x2-32-32.h

5 include files in \eval\nnue\architectures

add header guards

---

AUTHORS
src/Makefile
src/bitboard.h
src/endgame.cpp
src/evaluate.cpp
src/material.cpp
src/material.h
src/misc.cpp
src/pawns.cpp
src/position.cpp
src/position.h
src/psqt.cpp
src/search.cpp
src/thread.cpp
src/timeman.cpp
src/tt.cpp
src/tt.h
src/tune.cpp
src/types.h
src/ucioption.cpp

Update to SF master

---

src/eval/nnue/evaluate_nnue.cpp
src/eval/nnue/evaluate_nnue.h
src/eval/nnue/evaluate_nnue_learner.cpp
src/eval/nnue/nnue_test_command.cpp
src/ucioption.cpp

add filename change from previous PR update evaluate_nnue.cpp
to evaluate_nnue_learner.cpp

Update evaluate_nnue_learner.cpp 

---

src/learn/learner.cpp

こんばんは。
convert_plainコマンドを有効化してみました。
convert_plain→convert_bin で元のbinファイルに戻ることを確認済みです。

enable convert_plain

---

script/pgn_to_plain.py

game result bugfix

---

src/Makefile

Add a new target profile-learn to the makefile by tweaking the original profile-build target to allow pgo optimization of the gensfen part of the learn binary. On my machine it gives 10% speed up to generation with Use NNUE=false and 7% with Use NNUE=true. However to see the benefits for Use NNUE=true you need to modify the default value of Use NNUE to true in ucioption.cpp (and the default net needs to be available in the src folder) before compile. This is because the "benchmark" for pgo is a gensfen command that use these default values.
I'm not a Makefile expert and my implementation may not be very clean. Feedback appreciated.

PGO for data generation

---

src/Makefile
src/eval/evaluate_common.h
src/learn/convert.cpp
src/learn/gensfen.cpp
src/learn/learn.h
src/learn/learner.cpp
src/learn/multi_think.h

I've cleaned up pretty much everything in learner.cpp.
- Spread it across 3 files - gensfen, learner, conver. 
- Reorder includes and defines
- Improve bracing consistency
- Indendation consistency.
- Break long lines.
- Improve identifier names
- Break up some functions
- Use std::unique_ptr for the buffers
- Improve comments
- Make the book stuff be behind `#define USE_BOOK`
I limited myself to non-functional transformation, so unless I've done goofed everything should work the same as previously. But please verify if everything is working as expected before merging.
The code can still be improved by separating smaller parts, but I feel like this is enough for now.

General cleanup of learner.cpp.

---

src/learn/convert.cpp
src/learn/gensfen.cpp
src/learn/learner.cpp

Fix compilation issues brought up on discord.

Fix compilation issues.

---

src/Makefile

makes it a little easier to change the BLAS library used,
doesn't hardcode the mingw headers. Works on Linux with openblas installed.
Should be no change on Windows.

Define BLAS variables in Makefile

---

.travis.yml

second try, looks like this is the right package name

fix openblas package name?

---

src/Makefile

Fix #115. Only add -s flag to the linker if debug=no

---

.travis.yml
src/learn/learner.cpp
tests/instrumented_learn.sh

should presumably not be merged unless CI passes on this PR.

add more CI, instrumented runs

---

.travis.yml
src/learn/gensfen.cpp
src/learn/learning_tools.h
src/nnue/evaluate_nnue_learner.cpp
src/nnue/trainer/trainer.h
src/nnue/trainer/trainer_input_slice.h

`-Werror` for `learn` target was removed because it caused tests fail.  I removed compile warnings, and added `-Werror` to the compile option in CI.

Added -Werror to the compile option in CI

---

src/Makefile
src/learn/learn.cpp
tests/instrumented_learn.sh

fixes a small issue, with ponder
Probably the learning command can be improved a bit, so that despite the limited data, the code coverage is better.

Add a learning command to CI

---

src/learn/learn.cpp

declare a few variables atomic.
Other races remain...

Fix some races in learning

---

src/learn/learn.cpp

fixes https://github.com/nodchip/Stockfish/issues/160

Add initialization also to learning patch

---

src/nnue/features/castling_right.cpp

Fix castling rights feature encoding.

---

src/learn/learn.cpp
src/learn/multi_think.cpp
src/search.cpp
src/search.h
src/syzygy/tbprobe.h
src/thread.cpp
src/thread.h

they were not correct. Unfortunately, also restores the race on RootInTB

Revert earlier TB changes.

---

README.md
src/evaluate.h
src/learn/learn.cpp
src/learn/learn.h
src/nnue/features/castling_right.cpp
src/nnue/features/castling_right.h
src/nnue/features/enpassant.cpp
src/nnue/features/enpassant.h
src/nnue/features/feature_set.h
src/nnue/features/half_kp.cpp
src/nnue/features/half_kp.h
src/nnue/features/half_relative_kp.cpp
src/nnue/nnue_architecture.h
src/position.cpp
src/syzygy/tbprobe.h

This restores the original "lambda" option and default net architecture, while provide fully functional support to other net architectures for future experiments.
Improved README to accommodate changes to parameters, and minor code reformat to make future merges easier.

Restore lambda and gradient function post-merge and minor fixes.

---

src/evaluate.cpp
src/evaluate.h
src/misc.cpp
src/nnue/features/feature_set.h
src/nnue/nnue_feature_transformer.h
src/nnue/nnue_test_command.cpp
src/search.cpp

Potentially fix uninitialized value which might caused CI failures.

Merge SFdev

---

src/learn/gensfen.cpp

Remove unused code and magic numbers

Minor cleanups

---

src/thread.cpp
src/thread.h
src/uci.cpp

This introduces the ability to execute arbitrary tasks on stockfish's thread pool.

Allow execution of arbitrary tasks on the stockfish's thread pool.

---

src/nnue/trainer/trainer.h

Fix assertion in trainer

---

src/learn/learn.cpp
src/nnue/evaluate_nnue_learner.cpp
src/nnue/evaluate_nnue_learner.h
src/nnue/trainer/trainer_affine_transform.h
src/nnue/trainer/trainer_clipped_relu.h
src/nnue/trainer/trainer_feature_transformer.h
src/nnue/trainer/trainer_input_slice.h
src/nnue/trainer/trainer_sum.h

This is in preparation for using the stockfish's internal thread pool for parallelization within propagate/backpropagate.

Pass ThreadPool to update_parameters, propagate, and backpropagate.

---

src/nnue/trainer/trainer_feature_transformer.h

This PR optimizes clipping in the trainer feature transformer. It's a general effort to squeeze every bit of performance from sequential code in the trainer. I tested this by a short training run and didn't note any anomalies.

Optimize feature transformer clipping.

---

src/nnue/trainer/trainer_input_slice.h

This makes the input slice logic run in parallel for different batches. I also spread out the logic into three loops because I hate the codegen for the old version and I think it's cleaner like this.

Parallelize input slice trainer backprop.

---

src/nnue/trainer/trainer_clipped_relu.h

This optimizes the clipped relu in the trainer, similar to how it's done in the feature transformer. An ongoing effort to optimize all sequential parts in the learner. Tested with a small learning run.

Optimize trainer clipped relu propagate

---

src/learn/learn.cpp

This PR adds output of the loss calculated for each calc_loss cycle and a running average between evalsaves.

Output loss more often.

---

docs/learn.md
src/learn/learn.cpp

Add gradient clipping.

---

src/learn/gensfen.cpp

This case arises sometimes when using `ensure_quiet` for gensfen. Previously the sides could have been assumed to be flipping every entry.

Fix result assigned for a psvector when the positions are not continuous.

---

script/shuffle_binpack.py

This python tool shuffles the chunks (usually around a MB in size) in a .binpack file.

Add binpack coarse shuffle tool.

---

script/pgn_to_plain.py

in case a score can be parsed from the comment field in the pgn, add it to the output.
This form works for the fishtest pgns, and is quite common (cutechess-cli among others).

Enhance pgn_to_plain.py

---

script/pgn_to_plain.py

Bug fix: flipping score is not needed for fishtest, make this optional.

Make score sign flip optional

---

src/learn/opening_book.h

This fixes a potential race in OpeningBook::next_fen

Make next_fen in opening_book a critical section

---

docs/learn.md
src/learn/learn.cpp
src/learn/sfen_reader.h

This PR makes it easier to manipulate the filtering done during the validation data loading. Also `smart_fen_skipping_for_validation` option is added that applies quiet position filtering for the validation data.

Simple filtering for validation data.

---

src/learn/learn.cpp

This PR does a 'manual' depth 1 search instead of the stateful `search(pos, 1)` where qsearch and move ordering matters. Also require the best move to have a strictly higher score than the next one.

More deterministic move accuracy validation.

---

docs/gensfen_nonpv.md
src/Makefile
src/evaluate.cpp
src/learn/gensfen_nonpv.cpp
src/learn/gensfen_nonpv.h
src/thread.h
src/uci.cpp

Currently for experimentation. This gensfen takes positions from Eval::evaluate and rescores them later.

Add gensfen_nonpv

---

script/shuffle_binpack.py

this optional argument allows for splitting the input binpack in multiple output binpacks while shuffling.

Add split_count argument to shuffle_binpack.py

---

src/learn/learn.cpp

Prevent q_ in loss calculation from reaching values that would produce NaN

---

src/learn/sfen_reader.h

master's implementation exits the sfen reader worker as soon as end of the file is found. This discards up to 10M sfens. This PR fixes the behaviour. Fixes #271

Correctly handle the last batch of data in sfen_reader

---

.travis.yml
src/learn/gensfen.cpp
src/learn/learn.cpp
src/learn/sfen_reader.h

Let's see what errors we get...

Add thread sanitized run for instrumented_learn

---

docs/stats.md
src/Makefile
src/learn/stats.cpp
src/learn/stats.h
src/uci.cpp

... that allows gathering statistics from a .bin or .binpack file. Initially only support position count.
See `stats.md` for explanation and usage.

Add `gather_statistics` command

---

docs/gensfen_nonpv.md

Fix minor typo in documentation for gensfen

---

src/extra/nnue_data_binpack_format.h

Fix relation between halfmove and fullmove clocks.

---

docs/learn.md
src/learn/learn.cpp

Change some `learn` parameter naming. Update docs.

---

src/learn/learn.cpp

This patch measures what move accurracy would be achieved on average by choosing moves randomly. The purpose is to have a comparison with the actual move %, which depends on how many legal moves there are.
Notes: When only quiet positions are considered, and for early nets, random move accuracy is even higher than depth 1 move accuracy. Move accuracy rises slightly during training, but it's marginal. This suggests that the nets are not as good for ordering moves in quiet positions as we previously thought.
Output preview:
```
- move accuracy = 3.3%
- random move accuracy = 3.95534%
```
Closes #302

Add random move accuracy for comparison.

---

src/extra/nnue_data_binpack_format.h

Add additional checks for en-passant possiblity when fixing the erroneus ep flag from a fen.

---

docs/stats.md
src/learn/stats.cpp

This patch adds some more statistics gatherers. For what was added see the changes in the docs.
Sample output.
```
w:\nnue\temp_sample>stockfish.exe
Stockfish 050421 by the Stockfish developers (see AUTHORS file)
info string Loaded eval file nn-c3ca321c51c9.nnue
gather_statistics input_file in.binpack max_count 1000000 all
Processed 1000000 positions.
Finished gathering statistics.
Results:
Number of positions: 1000000
White king squares:
56       91      108      161       76       58       92       66
219      444      458      330      370      427      381      253
381      913      985     1148      975     1206     1112      742
652     1385     1838     2315     2821     2379     2347     1533
999     2135     3306     4876     6341     6626     6148     2967
1783     3710     6094 …
```

More stats
